function tmpprocess

runtests({
    'test/toepgenTest.m', ...
    'test/toeplkreconstructTest.m', ...
    'test/fcirculantTest.m', ...
    'test/displaceTest.m', ...
    'test/toeplkgenTest.m', ...
    'test/tleyeTest.m', ...
    'test/toepeyeTest.m', ...
    'test/istoeplitzTest.m', ...
    'test/gencompressTest.m', ...
    'test/toeplkctransposeTest.m', ...
    'test/toeplksquareTest.m', ...
    });


end