function tmpprocess

runtests({
    'test/toepgenTest.m', ...
    'test/toeplkreconstructTest.m', ...
    'test/fcirculantTest.m', ...
    'test/displaceTest.m', ...
    'test/toeplkgenTest.m', ...
    });


end